### ISSUE TITLE
如果创建ｐｏｄ时不使用eni，使用vpc，是否有路由条目条数的限制

### ISSUE THREAD

**Issue by zhenfdfs** [AliyunContainerService/terway#1]
文档里面关于这个的描述比较疑惑

> 结合VPC网络
> 纯ENI网络受限于每台ECS上ENI网卡数量，很多时候会显得不实用。一种方式是在ENI插件中支持VPC网络(现在的容器VPC网络，基于vrouter转发的方式)，用户可以选择一个Pod使用ENI网络还是VPC网络，如果选择ENI网络，Pod独占ENI网卡，否则Pod只分配一个VPC内能用的IP地址。 优先级P2
> 

在ENI插件中支持VPC网络，Pod只分配一个VPC内能用的IP地址，这个不是很理解，说的意思是podcidr属于vpc网段，pod 分配的ｉｐ在vrouter路由表里存在的？但是我没在代码里面找到路由表相关的api的调用

**Comment by zhenfdfs** [comment]
alicloud-controller-manager/cloud-controller-manager/controller/route/route_controller.go

**Comment by denverdino** [comment]
目前还会受限于vrouter路由表条目，配合后续阿里云网络能力发布，稍后会放出另外一种支持方式

**Comment by zhenfdfs** [comment]
await for new version

**Comment by BSWANG** [comment]
@zhenfdfs Hi, The new version based on `eni+multiip` have committed. You can test the example deployment `https://github.com/AliyunContainerService/terway/blob/master/terway-multiip.yml`

**Comment by zhenfdfs** [comment]
ok
