### ISSUE TITLE
terway如何配置通过内网调用阿里云API

### ISSUE THREAD

**Issue by chendanshuang** [AliyunContainerService/terway#105]
安全需求上，存在某些node是没有直接访问公网的权限的，terway无法正常调通阿里云API，有什么方法吗？

**Comment by BSWANG** [comment]
@chendanshuang 在支持内网API调用的Region，Terway会自动使用内网的IP地址进行调用的

**Comment by chendanshuang** [comment]
@BSWANG 感谢。这个实现是基于什么怎么做到的，privatezone cname吗，有具体的文档吗？我们账号环境需要设置什么不，比如privatezone？

**Comment by BSWANG** [comment]
> @BSWANG 感谢。这个实现是基于什么怎么做到的，privatezone cname吗，有具体的文档吗？我们账号环境需要设置什么不，比如privatezone？

对于已经支持内网地址调用的region，在ECS中解析对应region的openapi域名会自动返回内网的地址，不需要privatezone，但目前还有些region还暂时不支持
