### ISSUE TITLE
terway启动报错“open /var/lib/cni/terway/pod.db: no such file or directory”

### ISSUE THREAD

**Issue by HarryZheng0907** [AliyunContainerService/terway#112]
我是在阿里云的ecs上自建k8s，在部署terway的时候，terway的pod报如下错误：
time="2020-06-29T08:14:51Z" level=info msg="Starting terway of version: 7da5160"
time="2020-06-29T08:14:51Z" level=info msg="got config: &{Version:1 AccessId:****** AccessSecret:****** ServiceCIDR:10.96.0.0/12 VSwitches:map[] MaxPoolSize:5 MinPoolSize:0 Prefix: SecurityGroup: HotPlug: EniCapRatio:0 EniCapShift:0} from: /etc/eni/eni.json"
time="2020-06-29T08:14:51Z" level=info msg="alicloud: clientmgr, use accesskeyid and accesskeysecret mode to authenticate user. without token"
time="2020-06-29T08:14:51Z" level=fatal msg="error init k8s service: failed init db storage with path /var/lib/cni/terway/pod.db and bucket pods: open /var/lib/cni/terway/pod.db: no such file or directory"
从错误看，是没有/var/lib/cni/terway这个文件夹，我自己创建了这个文件夹就能正常起来了，但是正常情况下应该不需要我自己创建该文件夹才对

**Comment by BSWANG** [comment]
模板中有声明这个hostPath的，应该会自动创建这个目录的，请问您的k8s版本是多少，是不是hostPath声明没有自动创建出来： https://github.com/AliyunContainerService/terway/blob/master/terway.yml#L148

**Comment by HarryZheng0907** [comment]
我的k8s版本是1.17.5,我看这个L148里面的mountPath是/lib/modules，也不是报错中提到的/var/lib/cni/terway

**Comment by BSWANG** [comment]
> 我的k8s版本是1.17.5,我看这个L148里面的mountPath是/lib/modules，也不是报错中提到的/var/lib/cni/terway

L150那里
https://github.com/AliyunContainerService/terway/blob/master/terway.yml#L150

**Comment by HarryZheng0907** [comment]
我看master分支有配这个hostpath
https://github.com/AliyunContainerService/terway/blob/40d06957943345053146a3b9e75da4394a382917/terway.yml#L152
但是v1.0.10分支是没有的，我按照master的改动，修改一下就可以了

**Comment by BSWANG** [comment]
好的，那我关掉这个issue了
