### ISSUE TITLE
关于ENI模式访问service网络的疑问

### ISSUE THREAD

**Issue by duanjiong** [AliyunContainerService/terway#134]
如docs/design.md#eni中所说， 访问service网络会经过veth网卡，数据包到达host net namespace之后， iptables/ipvs会dnat把service ip转换成目的pod ip， 这个时候发包正常。  当目的pod接收到数据包之后， 回包会经过vpc路由，之后会直接到达源pod的物理网卡， 这个时候数据包的源ip并不是service ip， 所以数据包应该会被丢弃？ 这个问题请问是如何处理的，是需要把kube-proxy中的masqueradeAll设置成true？

ps：我并没有阿里云的环境， 所以并不能验证这个问题，以上分析纯粹是理论分析

**Comment by BSWANG** [comment]
> 如docs/design.md#eni中所说， 访问service网络会经过veth网卡，数据包到达host net namespace之后， iptables/ipvs会dnat把service ip转换成目的pod ip， 这个时候发包正常。 当目的pod接收到数据包之后， 回包会经过vpc路由，之后会直接到达源pod的物理网卡， 这个时候数据包的源ip并不是service ip， 所以数据包应该会被丢弃？ 这个问题请问是如何处理的，是需要把kube-proxy中的masqueradeAll设置成true？
> 
> ps：我并没有阿里云的环境， 所以并不能验证这个问题，以上分析纯粹是理论分析

是的，需要让kube-proxy的masqueradeAll设置为true才行，这样都会走宿主机做SNAT
