### ISSUE TITLE
How to realize Ingress Egress traffic control

### ISSUE THREAD

**Issue by bianze** [AliyunContainerService/terway#138]
Hi, I have seen the ingress and egress traffic control parameter in driver setup interface, but no detail realization about it. Can you share about how to design and realize the traffic control in terway?

**Comment by gameking0124** [comment]
因为linux“控发不控收”，基于veth网卡对的特性，主机端的发送就是容器端的接收，于是用控制主机端veth的发送来控制容器端接收的目的。所以在terway中看到不管是ingress还是egress都是控发。没错吧？

**Comment by l1b0k** [comment]
Please ref 
https://github.com/AliyunContainerService/terway/blob/main/docs/qos.md
or
https://www.alibabacloud.com/help/zh/container-service-for-kubernetes/latest/configureqosforthepod
