### ISSUE TITLE
重启ecs后，设备主网卡变成eth2，造成路由策略与设备混乱，网络路由几乎不可用，请问这个如何解决。

### ISSUE THREAD

**Issue by yonghuili1** [AliyunContainerService/terway#141]

**Comment by yonghuili1** [comment]
看起来是网卡的启动顺序有问题

**Comment by BSWANG** [comment]
terway需要关闭系统默认的对弹性网卡的自动配置

* 可以检查下network服务的规则，看是否关闭了对其他网卡的自动配置
* 对于较新的操作系统也可能是使用的systemd-networkd，可以检查下它的对其他网卡的配置方式
