### ISSUE TITLE
ARP解析问题

### ISSUE THREAD

**Issue by bianze** [AliyunContainerService/terway#159]
把host namespace的ipvlan slave设备(这里用ipvl0指代)IP地址设置成与master IP地址一致，子网掩码32位，scope为host且加上NOARP flag时，从master设备进来的包都会进到ipvl0设备接收，出去时根据之前主机的默认路由直接走master设备发出，不经过ipvl0，这样看到arp表项里很多都是incomplete的，请问有遇到这个问题吗？
![image](https://user-images.githubusercontent.com/67493735/101641303-8eb46c80-3a6c-11eb-8ccc-db85be933c62.png)

**Comment by BSWANG** [comment]
@bianze 没有遇到这个问题，设置为no arp就是为了避免arp的incomplete，请问您的kernel版本是多少？

**Comment by bianze** [comment]
> @bianze 没有遇到这个问题，设置为no arp就是为了避免arp的incomplete，请问您的kernel版本是多少？

4.19的内核，因为设置成相同IP地址后，arp请求是从master发出去的，arp reply会送到ipvl0这个子设备，就算设置了no arp，这个arp的reply报文也无法再从master设备收到协议栈去处理吧，我这边测试是会arp解析不成功的

**Comment by xh4n3** [comment]
@bianze 
我们在 #207 中给 Pod 创建了一条 Pod 去 Host 的路由，避免其 MAC 地址与 IPVLAN 接口不匹配导致流量出到 VPC 中，同时在 Pod 内创建了 Host eth0 IP -> IPVLAN MAC 地址的 ARP 绑定，避免 NOARP 导致的 incomplete。

这样改完之后，Host -> Pod 的请求，去方向和回方向都会经过 IPVLAN 接口，不会绕道 VPC 了。

麻烦看下是否解答了您的疑问？:)

cc @BSWANG
