### ISSUE TITLE
Some suggestions for document

### ISSUE THREAD

**Issue by BetaCat0** [AliyunContainerService/terway#16]
Recently I was searching a CNI plugin for k8s cluster in aliyun cloud. After struggling through tons of nework plugins, I found `terway` is a good plugin that I can rely on. I realize that there exist some defaults in `terway` document after consulting @BSWANG some questions on DingTalk. I'd like to point them out in this issue :)
 1. Troubleshooting section
 2. Interpretation should be more detailed, both in readme and documents in aliyun(explaination of how `ENI` work, limitation of `terway`, advantage of `terway`. etc. )
 3. Migration(maybe?) routeway for other CNI(like for flannel, which is the default network plugin when setting up new k8s cluster on aliyun)
And, finally, thanks to every contributer in this project. Thank you all.

**Comment by BSWANG** [comment]
Troubleshooting tools: https://github.com/AliyunContainerService/terway/blob/master/docs/terway-cli.md

**Comment by BSWANG** [comment]
terway design: https://github.com/AliyunContainerService/terway/blob/master/docs/design.md

**Comment by BetaCat0** [comment]
Thanks :)
