### ISSUE TITLE
Calico IPAM 功能在terway网络插件上是否支持？ 什么时候才能推出地址池管理功能。

### ISSUE THREAD

**Issue by Yangstatus** [AliyunContainerService/terway#165]
阿里云k8s容器服务目前只支持Flannel和Terway插件，但是这两个插件都无法支持对Pool地址池的自定义管理，能否支持对ip pool地址池的管理配置。  目前我们遇到的问题 pod-cidr 地址划分了两个vpc交换机  172.29.104.0/21  172.29.96.0/21  这里想把这两个网段分别用于测试和生产。 但现在无法灵活管理和控制。

**Comment by l1b0k** [comment]
地址池是在 VPC 上分配的，你所使用的 Pod 网卡也是要和指定  switch 关联，这快在资源使用，调度方面还有问题。

可以将 生产、测试环境分别关联不同的节点，然后使用下面 配置方式，将 switch 和 节点进行关联
https://github.com/AliyunContainerService/terway/blob/master/docs/dynamic-config.md

**Comment by Yangstatus** [comment]
好的谢谢。 还有能否直接通过Node IPAM Controller  配置node podCIDR的网段， 使对应work节点上面的pod只能获取该cidr中的ip。  上面的分配方式是否也是同样的原理。  后续IPAM功能大概什么时候可以上线。

**Comment by l1b0k** [comment]
可以理解为一样的方式，将 CIDR 段分配到 node 上。
Terway 的化就是使用上面的 dynamic-config 将关联不同交换机CIDR 对应到不同节点， 这个应该能满足你的使用了吧

**Comment by Yangstatus** [comment]
这个应该是目前最好的方案了，如果后续能推出IPAM更好。不过我这边有个疑问，如果现有节点中得节点池已经关联了两个switch 分别是两个vpc网段，那么如何将node节点得terway插件中得configmap自定义为其中一个switch 。 还是说只能新建节点池绑定switch。我现在新创建得configmap 里面指定了其中一个switch ，但是terway-eniip 重启后挂载得依旧是之前得configmap，没有通过node labels匹配到新的配置文件上。

**Comment by l1b0k** [comment]
Terway 支持 Trunking 类型网络，可以灵活配置每个 Pod 的网段、交换机，支持固定 IP， 请参考文档:

https://www.alibabacloud.com/help/zh/container-service-for-kubernetes/latest/poduniquevswitch
or
https://github.com/AliyunContainerService/terway/blob/main/docs/terway-trunk.md

**Comment by Yangstatus** [comment]
精细化功能越来越完善了
