### ISSUE TITLE
terway插件辅助网卡主ip地址不可见，但是能ping通

### ISSUE THREAD

**Issue by songminglong** [AliyunContainerService/terway#184]
购买托管版容器服务集群，进入ECS节点后，应用想要使用辅助网卡ip地址，发现该辅助网卡绑定ECS后，并没有获取ip地址。
经过初步测试，发现从ECS/Pod都可以ping通该IP地址，请问该辅助网卡主ip地址在哪里配置的？实现基本原理是啥？应用怎么才能绑定该地址？

**Comment by l1b0k** [comment]
节点辅助网卡由Terway 管理，上面地址由 Terway 分配给 Pod 使用。kubectl get pod -A -o wide  看下地址是不已经分配到Pod 了

**Comment by songminglong** [comment]
这个指的是pod地址，这个没问题的。
我的意思是绑定到ECS虚机的辅助网卡主ip地址（不是辅助私网ip地址），该地址不可见，但是能ping通

**Comment by l1b0k** [comment]
同样会分配到PodIP，你查看PodIP 中没有吗？

**Comment by songminglong** [comment]
集群初始化后，在kube-system下面存在很多pod，是在哪一个pod里面？
我查看了terway eni pod里面也没有。

**Comment by l1b0k** [comment]
PodIP 是随机分配的 。kubectl get pod -A -o wide 看下地址是不已经分配到Pod 了？

**Comment by songminglong** [comment]
辅助网卡主ip地址，和辅助私网ip地址一样，作为pod可用ip地址，分配给pod使用了，已经看到了，thx

**Comment by songminglong** [comment]
完成
