### ISSUE TITLE
Decouple of ENI CURD

### ISSUE THREAD

**Issue by mars1024** [AliyunContainerService/terway#28]
Now, ENI CURD is done in eni daemon through aliyun openapi, which leads to some problems I think as below
1.  unable to do flow control on aliyun openapi, the frequency of requests increase with the size of the cluster
2. no ENI-related info stores in k8s, if we want to do something using ENI id or else, we have to get it from aliyun openapi
3. eni-daemon should not be upgraded frequently, if we use aliyun openapi sdk in daemon, we have to upgrade to follow the upgrade of sdk

So I think we can design a centralized ENI controller which to do jobs of ENI CURD and let eni-daemon connect  to it through CRD (watch) or ClusterIP (polling).

**Comment by l1b0k** [comment]
we have supported CRD based IPAM
