### ISSUE TITLE
钉钉群的号码是错的吗?搜索不到

### ISSUE THREAD

**Issue by penghuazhou** [AliyunContainerService/terway#281]
![image](https://user-images.githubusercontent.com/13001038/141882498-5aff9897-58f3-4167-827c-79c75886cb47.png)

![image](https://user-images.githubusercontent.com/13001038/141882456-5762606c-006f-4893-a8e7-b1c044f2bd21.png)

**Comment by l1b0k** [comment]
请搜索公开群组 
![image](https://user-images.githubusercontent.com/4043362/146727620-88f09a30-ef2e-4af1-aef4-75909a21d00c.png)

**Comment by penghuazhou** [comment]
thanks
