### ISSUE TITLE
hostport不工作

### ISSUE THREAD

**Issue by ermazi** [AliyunContainerService/terway#34]
安装terway以后，portmap无效，该怎么配置？

**Comment by BSWANG** [comment]
`hostport`可以通过[CNI plugin chain](https://karampok.me/posts/chained-plugins-cni/)来导入`portmap`插件来实现
具体可以修改模板中的cni_config的配置增加portmap来实现 https://github.com/AliyunContainerService/terway/blob/master/terway.yml#L75-L80

**Comment by shenshouer** [comment]
@BSWANG 
使用terway cni插件方式配置如下：
```
  10-terway.conf: |
    {
      "cniVersion": "0.3.0",
      "name": "terway",
      "plugins": [
        {
          "type": "terway"
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        },
        {
          "type": "portmap",
          "capabilities": {"portMappings": true}
        }
      ]
    }
```
结果Node出现NotReady状态
