### ISSUE TITLE
请教teway中network policy和eBPF的相关问题

### ISSUE THREAD

**Issue by BetaXOi** [AliyunContainerService/terway#458]
我注意到开发者有向cilium社区提交terway和cilium采用CNI chains方式使用的PR https://github.com/cilium/cilium/pull/14436
而当前terway的ipvlan模式下network policy是采用直接集成cilium组件的方式

我理解chains方式下terway负责ENI/EIP的资源管理、IPAM以及netlink的处理（ipvlan或veth等），而cilium负责加载eBPF实现network policy和其他可能的高级特性
而cilium自1.11版本废弃了ipvlan模式后，eBPF对于加速网络转发的处理自然仅针对于veth模式，那么在chains方式下，k8s集群中访问service的流程是否有额外的eBPF做加速转发？（我理解pod访问pod时，veth模式下eBPF加速网络转发应该和直接使用ipvlan模式性能基本一致，不知道是否正确）

而当前terway ipvlan模式集成cilium组件的方式下，eBPF除了实现network policy，是否有加速网络转发的实现？

最后，两种方式是否存在其他重要的区别以及待考量的点？后续terway会采用那种方式继续演进？

**Comment by l1b0k** [comment]
可以理解为
- ipvlan 处理非Service 流量
- ebpf 处理Service 流量

pod2pod 情况走 ipvlan ，会优于走 veth 路径

**Comment by chestack** [comment]
> 可以理解为
> 
> * ipvlan 处理非Service 流量
> * ebpf 处理Service 流量
> 
> pod2pod 情况走 ipvlan ，会优于走 veth 路径

@l1b0k 请教下，k8s集群中应用间东西向互访基本都是通过svc，很少有pod之间直接通过pod ip互访的情况，所以pod ns下面的 ipvlan 子接口其实流量很少，ipvlan相比其他虚拟网络技术的高性能优势 并没有得到很好的利用，可以这么理解吗？ 谢谢

**Comment by l1b0k** [comment]
@chestack pod 内所有流量都会从 ipvlan 接口出去，svc 也是在容器内就DNAT 后直接出去的，相比veth 绕到节点会有很大差异。

**Comment by BetaXOi** [comment]
感谢大佬的解答，还有个问题哈

**Comment by l1b0k** [comment]
> 
会提前执行 `cilium preflight register-crd` 来同步 CRD

**Comment by BetaXOi** [comment]
> @l1b0k 看到您是cilium alibabacloud ipam operator的作者，所以有个相关的问题 也想请教下. 具体问题 在 [cilium/cilium#25698 (comment)](https://github.com/cilium/cilium/pull/25698#issuecomment-1568004571)
> 
> 就是对于 cilium使用 cloud vpc ipam 模式的场景，跨节点通信的情况 节点的网卡是否应该对该节点上的pod 做ARP代答呢, 这个ARP代答是cilium ebpf实现还是 vpc 辅助IP支持，谢谢

在云计算场景下，ARP的处理是底层虚拟网络流表代答处理的，即底层虚拟网络明确的知道哪个IP在哪个网卡上，所以计算节点上的流表直接做ARP代答

**Comment by chestack** [comment]
再请教一个问题 @l1b0k @BSWANG @BetaXOi 

https://github.com/cilium/cilium/pull/15160   和  terway做cni 集成cilium ebpf实现 kube-proxy replacement 和 network policy，这两种使用场景的主要区别是什么，实际使用中建议使用哪一种，谢谢

**Comment by BSWANG** [comment]
> 再请教一个问题 @l1b0k @BSWANG @BetaXOi
> 
> Alibaba 同时支持：
> 
> * [cilium alibabacloud ipam operator](https://github.com/cilium/cilium/pull/15160)
> * terway做cni, 集成cilium ebpf实现 kube-proxy replacement 和 network policy
> 
> 这两种方案的主要区别(例如 veth vs. ipvlan的性能上)是什么，实际使用中分别适用什么场景，谢谢

terway是ipvlan的L2模式，在宿主机的协议栈上不会经过iptables/路由等开销，性能上ipvlan在延迟和稳定性是好于veth模式的。
阿里云的产品上使用的terway做cni的，原因是terway来做cni可以做比较灵活的IP管理策略，比如固定IP，指定Pod安全组、交换机等。Cilium仅用于service和networkpolicy的实现上。

**Comment by cyclinder** [comment]
> > 
> 
> 会提前执行 `cilium preflight register-crd` 来同步 CRD

你好，这条命令是在哪个步骤被执行的呢

**Comment by l1b0k** [comment]
> 

可在安装Terway 组件前用 Job 跑下。
更多讨论可以移步  https://github.com/AliyunContainerService/terway/discussions
