### ISSUE TITLE
0009-add-cmd-to-register-crd.patch中的bug

### ISSUE THREAD

**Issue by lyxly** [AliyunContainerService/terway#502]
++	preflightCmd.Flags().StringVar(&k8sAPIServer, "k8s-api-server", "", "Kubernetes api address server (for https use --k8s-kubeconfig-path instead)")
++	preflightCmd.Flags().StringVar(&k8sKubeConfigPath, "k8s-kubeconfig-path", "", "Absolute path of the kubernetes kubeconfig file")
这里是否应该是，按照上面的patch合入运行有误：
一直提示：Error: unknown flag: --k8s-kubeconfig-path
按照如下合入可以正常运行：
++	registerCRDCmd.Flags().StringVar(&k8sAPIServer, "k8s-api-server", "", "Kubernetes api address server (for https use --k8s-kubeconfig-path instead)")
++	registerCRDCmd.Flags().StringVar(&k8sKubeConfigPath, "k8s-kubeconfig-path", "", "Absolute path of the kubernetes kubeconfig file")

**Comment by l1b0k** [comment]
用的什么版本的 Cilium，在我这里没有这个问题
