### ISSUE TITLE
Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by wenzt** [AliyunContainerService/terway#584]
terway版本：Starting terway of version: 161324c

不停的打以下日志：
2024/03/07 19:21:59 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:00 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:01 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:02 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:03 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:04 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:05 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:06 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:07 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:08 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:09 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:10 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:11 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
time="2024-03-07T19:22:11Z" level=error msg="alicloud: clientmgr, error get ram role token [Get http://100.100.100.200/latest/meta-data/ram/security-credentials/OceanNode: dial tcp 100.100.100.200:80: socket: too many open files]\n"
2024/03/07 19:22:12 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:13 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:14 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:15 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:16 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:17 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:18 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:19 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:20 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:21 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:22 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:23 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s
2024/03/07 19:22:24 http: Accept error: accept tcp [::]:12345: accept4: too many open files; retrying in 1s

**Comment by BSWANG** [comment]
看起来应该是机器上有socket泄露， 可以看看netstat -na命令的输出吗？
