### ISSUE TITLE
eni ipvlan l2 mode network policy

### ISSUE THREAD

**Issue by firemiles** [AliyunContainerService/terway#73]
I found terway use ipvlan l2 mode for eni multiple ip, does it support calico network policy?

**Comment by zhiyuan0x** [comment]
No, It doesn't support yet. But the work for ipvlan's network policy is in process.

**Comment by firemiles** [comment]
@zhiyuan0x thx reply，I'm looking forward to this feature

**Comment by alpha-li** [comment]
What is the solution and opinion? Since it is well known that the source ip must not be SNATed when accessing services, how to solve this problem?

**Comment by Colstuwjx** [comment]
related PR should be [this](https://github.com/cilium/cilium/pull/10251), I also wonder that why we don't use calico, and choose cilium as the network policy backend. It could be more clearly if we could clarify about this.
