### ISSUE TITLE
terway是否支持calico的“application layer policy”

### ISSUE THREAD

**Issue by jenningsloy318** [AliyunContainerService/terway#80]
Hi，
对于terway （eni or vpc模式），不知道现在对于application layer policy的支持事怎么样的，application layer policy支持对API call 方法和路径进行限制，不知道现在的支持状态事如何的？

**Comment by BSWANG** [comment]
Terway的network policy采用的calico felix版本是3.5，理论上是支持的。

**Comment by jenningsloy318** [comment]
我看到calico的配置里面启用了FELIX_POLICYSYNCPATHPREFIX才能使用application layer policy，但是terway 并灭有启用这个参数，所以很怀疑
```
            - name: FELIX_POLICYSYNCPATHPREFIX
              value: "/var/run/nodeagent"              
```
