### ISSUE TITLE
请问一下terway是专门为阿里云环境做的吗，腾讯云的vpc能不能用？

### ISSUE THREAD

**Issue by zong400** [AliyunContainerService/terway#82]
另外如果想把calico替换为terway有可行性吗

**Comment by BSWANG** [comment]
目前是只支持aliyun的，从腾讯云的文档看，[是支持弹性网卡和辅助IP的](https://cloud.tencent.com/document/product/215/15755#.E5.BC.B9.E6.80.A7.E7.BD.91.E5.8D.A1.E7.9B.B8.E5.85.B3.E6.8E.A5.E5.8F.A3)，理论上可以在terway的penapi调用中增加腾讯的provider来支持.
